### ISSUE TITLE
PeptideSpectrum with Single match

### ISSUE THREAD

**Issue by heejongkim** [OrgMassSpec/OrgMassSpecR#4]
Hi,

As I'm working on some extreme cases of PSMs, I encountered the situation where there's only one matched ion, which breaks PeptideSpectrum by confessing the following error:
Warning: Error in if: missing value where TRUE/FALSE needed
at
if((identifications$expt_mz[i+1] - identifications$expt_mz[i]) / x_range < 0.025 & 
         all.equal(identifications$expt_intensity[i], 100) != TRUE)
where identifications$expt_mz[i+1] is NA.

What would be your recommended way to handle this?
Thanks,
hee jong

**Comment by OrgMassSpec** [comment]
Hi - This is a bug. I believe I've fixed it. Please see OrgMassSpecR version 0.5-2 here: [https://github.com/OrgMassSpec/OrgMassSpecR](url). (Download OrgMassSpecR 0.5-2.tar.gz and install the package). Thanks,
Nate

**Comment by heejongkim** [comment]
Hi,

After installing the dev source version, I'm still getting the same issue.
Please check the example below:

    for(i in 1:(num_identifications - 1)) {
      print(identifications)
      	#    expt_mz expt_intensity ms1seq   ms1z1   ms1z2   ms1z3 ms2seq ms2type   ms2mz error
		# 1 475.2768              5 tkqtar 732.436 366.722 244.817   qtar  [y4]1+ 475.262 0.015
      print(identifications$expt_mz[i+1])
      	#  [1] NA
      print(identifications$expt_mz[i])
      	#  [1] 475.2768
      print(x_range)
      	#  [1] 1400
      print((identifications$expt_mz[i+1] - identifications$expt_mz[i]) / x_range)
      	#  [1] NA
      print(all.equal(identifications$expt_intensity[i], 100))
      	#  [1] "Mean relative difference: 19"
      if((identifications$expt_mz[i+1] - identifications$expt_mz[i]) / x_range < 0.025 & 
         all.equal(identifications$expt_intensity[i], 100) != TRUE)
        #  Warning: Error in if: missing value where TRUE/FALSE needed

**Comment by OrgMassSpec** [comment]
Please send a reproducible example including the peptide sequence and experimental mass spectrum. (You may need to use dput() to include the mass spectrum. Thank you.

**Comment by heejongkim** [comment]
[custom_mass.txt](https://github.com/OrgMassSpec/OrgMassSpecR/files/1219360/custom_mass.txt)
[expt_ms2.txt](https://github.com/OrgMassSpec/OrgMassSpecR/files/1219361/expt_ms2.txt)

expt_ms2 <- dget('expt_ms2.txt')
custom_mass <- dget('custom_mass.txt')
theo_ms2 <- FragmentPeptide("tkqtar", fragments = "by", custom = custom_mass)
matched_ms2_peaks <- PeptideSpectrum(expt_ms2, theo_ms2)

Hope this is sufficient to reproduce the error.

Thanks,
hee jong

**Comment by OrgMassSpec** [comment]
Hi - Your example worked. The plot is shown below. Please verify the OrgMassSpecR version is 0.5-2. 
![output](https://user-images.githubusercontent.com/5410314/29236526-68f3cbe6-7ec0-11e7-9eb3-ae829af711cb.png)

**Comment by heejongkim** [comment]
Ahhhh.
It's stupid of me. Forgot to remove local PeptideSpectrum function which I used to identify the location of the error. After removing it, it works well!
Thank you for the update.

Best,
hee jong
